name: Studio Zip Generator
on:
  # Triggers the zip generator workflow on push for the dev, stage, main, preview, and previous branch.
  push:
    branches: [ develop,stage,main,preview,previous ]
    paths:
      - 'reference/**'

jobs:
  api_validator: 
    uses: Fiserv/remote-actions/.github/workflows/github-yaml-validator.yaml@fix-validator
    secrets: inherit
  api-zip-generator:
    needs: api_validator
    uses: Fiserv/remote-actions/.github/workflows/github-zip-generator.yaml@fix-validator
    if: ${{ !contains( needs.api_validator.outputs.statuscheck , 'SKIPPED')}}
    secrets: inherit
